# Replace the text below to customize your site
site_name: minnie-at-iaac
site_description: Master in Design for Emergent Futures 2023-24
site_author: Emmanuelle Pangilinan
copyright: Copyright 2023 Minnie/Emmanuelle Pangilinan
repo_name: 'minnie-at-iaac.github.io'
site_url: https://minnie-at-iaac.github.io
repo_url: 'https://github.com/minnie-at-iaac/minnie-at-iaac.github.io'


nav:
  - About: about/me.md
  - Term 1:
      - Landing Week: 
        - Landing Week: term1/01-Landing-week/Landing.md
        - Intros: term1/01-Landing-week/Intros.md
#        - Tours: term1/01-Landing-week/Tours.md
      - Documenting Design: term1/02-Documenting-design/Documenting-design.md
      - Design Studio 01: 
        - Design Studio: term1/03-Design-studio/Design-studio-01.md
        - Intervention 01: term1/03-Design-studio/Intervention-01.md
        - Story-telling: term1/03-Design-studio/Story-telling.md
        - Intervention 02: term1/03-Design-studio/Intervention-02.md
      - Atlas of Weak Signals: term1/04-Atlas-of-weak-signals/Atlas of Weak Signals.md
      - Machine Paradox: 
        - Machine Paradox: term1/05-Machine-Paradox/Machine-Paradox.md
        - Forensic Report: term1/05-Machine-Paradox/Forensic-Report.md
        - Triggered: term1/05-Machine-Paradox/Triggered.md
      - Living with Ideas:
        - Living with Ideas: term1/06-Living-with-Ideas/Living-with-Ideas.md
        - Making a Companion: term1/06-Living-with-Ideas/Making-a-Companion.md
      - Bio and Agri Zero: 
        - Biology Zero: term1/07-Bio-and-Agri-Zero/Biology-Zero.md
        - Agriculture Zero: term1/07-Bio-and-Agri-Zero/Agriculture-Zero.md
      - Design with Others:
        - term1/08-Design-with-others/Design-with-others.md
      - Extended Intelligences: term1/09-Extended-Intelligence/Extended-Intelligence.md
      - Design Dialogues: term1/10-Design-Dialogues/Design-Dialogues.md
      #- Extra:
      #  - Git Problems: term1/02-Documenting-design/Git-problems.md
      #  - Books: term1/99-Notes/Readables.md
      #  - Dialogues Notes: term1/99-Notes/DD-Notes.md
  - Term 2:
      - Design Studio: term2/00-Design-Studio/Design-Studio.md
      - Designing in a state of climate emergency: term2/01-Designing-Climate-Emergency/Day01.md
      - Communicating Ideas:
        - Communicating Ideas: term2/02-Communicating-Ideas/Communicating-Ideas.md
        - Tandem Project Video: term2/02-Communicating-Ideas/Tandem-Project.md
      - Designing with Values: term2/03-Designing-with-Values/Designing-with-values.md
      - Fair Future(s): term2/06-Fair-Futures/Fair-Futures.md
      - Digital Prototyping:
        - Module 01: term2/04-Digital-Prototyping/Module-01.md
        - Microchallenge 01: term2/04-Digital-Prototyping/Microchallenge-01.md
      - Measuring the World: term2/05-Measuring-the-world/Measuring-the-World.md
      - Designing with Extended Intelligences: term2/07-Extended-Intelligences/Extended-Intelligences.md
  - Master project:
      - Initial ideas: project/project.md
  - Side Quests:
    - Git Problems: term1/02-Documenting-design/Git-problems.md
    - Books: term1/99-Notes/Readables.md
    - Dialogues Notes: term1/99-Notes/DD-Notes.md


extra:
  social:
    # For other social icons at https://squidfunk.github.io/mkdocs-material/setup/adding-social-links/
    - icon: fontawesome/brands/instagram
      link: "https://instagram.com/kotsengkuba"
    - icon: fontawesome/brands/instagram
      link: "https://instagram.com/minniemakestoys"
    - icon: fontawesome/brands/linkedin
      link: "https://www.linkedin.com/in/minnie-pangilinan"

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: my-theme
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: black
  font:
    # See available fonts at https://fonts.google.com/
    text: Karla
    code: Inconsolata
  logo: images/logo_minnie.png
  favicon: images/logo_minnie.png
  features:
    - instant
    - header.autohide
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.prune
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

plugins:
  - search
  - git-revision-date-localized
  - glightbox:
       touchNavigation: true
       loop: true
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       skip_classes:
         - custom-skip-class-name
       auto_caption: false
       caption_position: bottom

markdown_extensions:
  - extra
  - smarty
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - md_in_html
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: 'docs'
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.escapeall:
        hardbreak: true
  - attr_list
  - pymdownx.tabbed:
        alternate_style: true
  

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css
