# Replace the text below to customize your site
site_name: Minnie's MDEF
site_description: Master in Design for Emergent Futures 2023
site_author: Emmanuelle Pangilinan
copyright: Copyright 2023 Emmanuelle Pangilinan
repo_name: 'minnie-at-iaac.github.io'
site_url: https://minnie-at-iaac.github.io
repo_url: 'https://github.com/minnie-at-iaac/minnie-at-iaac.github.io'


nav:
  - About: about/me.md
  - Term 1:
      - Landing: term1/01-Landing.md
      - AoWS: term1/02-Atlas of Weak Signals.md
  - Term 2:
      - digi: default-page.md
      - studio: default-page.md
  - Master project:
      - Initial ideas: project/project.md


extra:
  social:
    # For other social icons at https://squidfunk.github.io/mkdocs-material/setup/adding-social-links/
    - icon: fontawesome/brands/instagram
      link: "https://instagram.com/kotsengkuba"
    - icon: fontawesome/brands/instagram
      link: "https://instagram.com/minniemakestoys"
    - icon: fontawesome/brands/linkedin
      link: "https://www.linkedin.com/in/minnie-pangilinan"

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: yellow

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    # See available fonts at https://fonts.google.com/
    text: Space Grotesk
    code: Cutive Mono
  icon:
    logo: material/lightbulb-outline
  favicon: images/favicon.png
  features:
    - instant
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    #- navigation.tabs.sticky
    #- navigation.top
    #- navigation.tracking

plugins:
#  - search
#  - git-revision-date-localized:
#      fallback_to_build_date: true

markdown_extensions:
  - extra
  - smarty
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: 'docs'
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - pymdownx.tabbed

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css
